config/routes.rb
Rails.application.routes.draw do
  resources :buddie,only: [:index]
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :buddies do
  resources :messages,only: [:new,:create,:index,:show]
    member do
    get 'show_other_buddie'
  end
end
  resources :users do
    member do
      get :confirm_email
      resources :buddies

    end
  end
  resources :messages
end

app/models/message.rb
class Message < ApplicationRecord
  has_one :receving_buddie_id_
  has_one :sending_buddie_id
  validates :content,presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
require 'will_paginate/array'
def new
   @message = Message.new()
   @first_value = params.values()[2]
   @receving_buddie = Buddie.find(@first_value)
   session[:passed_variable] = @first_value
  end

  def create
   @message = Message.new(message_params)
   @first_value = session[:passed_variable]
   @receving_buddie_id = @first_value
   @message[:receving_buddie_id] = @receving_buddie_id
   @receving_buddie = Buddie.find(@receving_buddie_id)
   @message.date = Date.today
   @message.time = Time.now.strftime("%H:%M:%S")
   @buddies = Buddie.all
   @buddies.each do |b|
    if b.user_id == current_user.id
      @message[:sending_buddie_id] = b.id

    end
   end

    if @message.save
    flash[:success] = "Your message was sent successfully"
    redirect_to buddies_path(flash[:success])

   else

     render :new

   end

  end


  def index
   @buddies = Buddie.all
   @buddies.each do |b|
   if b.user_id == current_user.id
   @current_user_buddie_id = b.id
  end
 end


  @all_messages = Message.all
  @buddie_received_messages = []
  @buddie_sent_messages = []

  @all_messages.each do |m|
  if m[:receving_buddie_id] == @current_user_buddie_id
   @buddie_received_messages << m
  end
  if m[:sending_buddie_id] == @current_user_buddie_id
     @buddie_sent_messages << m
   end

  end

@buddie_sent_messages = @buddie_sent_messages.paginate(page: params[:page],per_page: 5)
@buddie_received_messages = @buddie_received_messages.paginate(page: params[:page],per_page: 5)


 end

 def show
  @message = Message.find(params[:id])
end


 private

def message_params


  params.require(:message).permit(:content)

 end

end

app/views/messages/index.html.erb
<script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>

<div class="index_banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/erezfriemagor/image/upload/v1545252788/pexels-photo-235554.jpg');">
<h2>received messages</h2>
<table style="width:100%">
<tr>
    <th>From</th>
    <th></th>
   <th>Received</th>
  </tr>
<%@buddie_received_messages.each do |m|%>
 <tr>
    <td><%= link_to buddy_path(m[:sending_buddie_id]) do %><%=Buddie.find(m[:sending_buddie_id]).name%></td><%end%>
    <td> <%= link_to buddy_path(m[:sending_buddie_id]) do %>
     <div class="trainershowcircle" style="background-image: url(<%=Buddie.find(m[:sending_buddie_id]).photo%>)"></div><%end%>

   </td>

    <td> <%= link_to buddy_message_path(m[:receving_buddie_id],m.id) do %>
      <%=m.date%> <%=m.time.hour%>:<%=m.time.min%></td><%end%>
   </tr>
 <%end%>

 <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @buddie_received_messages %>
    </div>
    <%= will_paginate @buddie_received_messages, :container => false %>
  </div>



 <tr>
  <td><h2>sent messages</h2></td>
</tr>
<tr>
    <th>To</th>
    <th></th>
    <th>Sent</th>
  </tr>
<%@buddie_sent_messages.each do |m|%>
 <tr>
    <td><%= link_to buddy_path(m[:receving_buddie_id]) do %><%=Buddie.find(m[:receving_buddie_id]).name%></td><%end%>
    <td> <%= link_to buddy_path(m[:receving_buddie_id]) do %>
     <div class="trainershowcircle" style="background-image: url(<%=Buddie.find(m[:receving_buddie_id]).photo%>)"></div><%end%>

   </td>

    <td> <%= link_to buddy_message_path(m[:receving_buddie_id],m[:id]) do %>
      <%=m.date%> <%=m.time.hour%>:<%=m.time.min%></td><%end%>
   </tr>
 <%end%>

</table>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @buddie_sent_messages %>
    </div>
    <%= will_paginate @buddie_sent_messages, :container => false %>
  </div>


</div>

<style>
  .page_info{color:white;}
.index_banner{margin-top:-22px;}
 .trainershowcircle {
     position: relative;
     border-radius: 49.99%;
     width: 100px;
     height: 100px;
     background-size: cover;
     border: solid 1px white;
     box-shadow: 3px 3px 3px 3px;
   }
   .index_banner{height:100vh;}
   table{color:white;}
   h2{color:green;margin-top:26px;}
}
</style>
<script>

</script>

app/views/messages/new.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/erezfriemagor/image/upload/v1556534197/adult-beautiful-brunette-1549280_1.jpg');">
<div class="create_profile">
   <%=simple_form_for Message.new do |f| %>
 <div class="input">write to <%=@receving_buddie.name%></div>
   <%= f.text_area :content,label: false, minlength: "20", maxlength: "400", placeholder: "type your message",cols: "40",rows: "8", contenteditable: "true"%>
    <div><%= f.button :submit,'submit', class: "btn-success"%><% end %>

   </div>
 </div>
</div>

<style>
#message_content
{
  width:400px;
  height:200px;
  margin-left:5px;
  padding-bottom:175px;
  height:auto;
}
 .input
 {
 font-size: 2.3vh;
 font-weight: lighter;
 color: white;
 font-style: bold;
 height: 2vh;
 margin-bottom: 1.7vh;
 margin-left:25px;
 }
.btn-success
{
  margin-left:25px;
  margin-top:5px;

}
.banner
{

  height:90vh;
}

</style>

app/views/messages/show.html.erb
<div class="index_banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/erezfriemagor/image/upload/v1547594461/pexels-photo-1688253.jpg');">
   <%if (Buddie.find(@message[:sending_buddie_id]).user_id != current_user.id )%>
<table>
<tr>
    <th>From</th>
    <th>     </th>
    <th>Received</th>
  </tr>
<tr>

<td><%= link_to buddy_path(@message[:sending_buddie_id]) do %><%=Buddie.find(@message[:sending_buddie_id]).name%> </td><%end%>
<td><%= link_to buddy_path(@message[:sending_buddie_id]) do %><div class="trainershowcircle" style="background-image: url(<%=Buddie.find(@message[:sending_buddie_id]).photo%>)"></div></td><%end%>
<td> <%=@message.date%> <%=@message.time.hour%>:<%=@message.time.min%></td>
</tr>
</table>
<h3><%=Buddie.find(@message[:sending_buddie_id]).name%> said</h3>
<div id="content">
 <%=@message.content%>
</div>
 <%= link_to "reply",new_buddy_message_path(Buddie.find(@message[:sending_buddie_id])), class: "btn btn-primary"%>
</div>

<%else%>

<table>
<tr>
    <th>To</th>
    <th>     </th>
    <th>Sent</th>
  </tr>
<tr>

<td><%= link_to buddy_path(@message[:receving_buddie_id]) do %><%=Buddie.find(@message[:receving_buddie_id]).name%> </td><%end%>
<td><%= link_to buddy_path(@message[:receving_buddie_id]) do %><div class="trainershowcircle" style="background-image: url(<%=Buddie.find(@message[:receving_buddie_id]).photo%>)"></div></td><%end%>
<td> <%=@message.date%> <%=@message.time.hour%>:<%=@message.time.min%></td>
</tr>
</table>
<h3>you said</h3>
<div id="content">
 <%=@message.content%>
<%end%>





<style>
.trainershowcircle {
     position: relative;
     border-radius: 49.99%;
     width: 100px;
     height: 100px;
     background-size: cover;
     border: solid 1px white;
     box-shadow: 3px 3px 3px 3px;
     margin-right:30px;
   }
table{margin-left:50px;}
.index_banner{height:100vh;color:white;}
#content{margin-left:30px;}
.btn-primary{margin-left:200px;}
</style>