config/routes.rb
Rails.application.routes.draw do
  resources :buddie,only: [:index]
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :buddies do
  resources :messages,only: [:new,:create,:index,:show]
    member do
    get 'show_other_buddie'
  end
end
  resources :users do
    member do
      get :confirm_email
      resources :buddies

    end
  end
  resources :messages
end

app/controllers/buddies_controller.rb
class BuddiesController < ApplicationController

  skip_before_action :authenticate_user!
  def index
  end
  def new
    if user_signed_in?
      @user = current_user
      @buddie = Buddie.new()

    end
  end


    def create
      if user_signed_in?
        current_user.update(has_profile: true)
        @user = current_user
        @buddie = Buddie.new(buddie_params)
        @buddie.user_id = @user.id
        @buddie.address = @buddie.countryname + " " + @buddie.town + " " +  @buddie.neighborhood
      end

      if @buddie.save

        flash[:success] = "You have created a profile successfully"
        redirect_to root_path(flash[:success])

     else
       if @buddie.name == ""

        flash[:name] = "please enter your name"
       end
       if @buddie.hobby == ""
        flash[:hobby] = "please enter your hobby"
       end
       if @buddie.town == ""
        flash[:town] = "please enter your town"
       end
       if @buddie.gender == ""
        flash[:town] = "please enter your gender"
       end



         flash[:faill] = "profile was not created"
         render :new



    end
    end
    def show

      @buddie = Buddie.where(user_id:current_user.id)


    end

    def show_other_buddie

       @buddie = Buddie.find(params[:id])


    end

    def index
      if (params[:town].blank? == false)
      address = params[:country] + " " + params[:town]
     end
      location = Geocoder.coordinates(address)
      if ((params[:town].present?) || (params[:gender].present?) || (params[:age].present?) || (params[:hobby].present?) )
        query = params[:town] + " " + params[:gender] + " " + params[:age] + " " + params[:hobby]
        if location != nil
        @buddies  = Buddie.multy_search(query).paginate(page: params[:page],per_page: 12).near(location,params[:distance].to_i + 10)
        else
        @buddies  = Buddie.multy_search(query).paginate(page: params[:page],per_page: 12)
        end
      else
      @buddies = Buddie.paginate(page: params[:page],per_page: 12)
    end

    end


    private

    def buddie_params


      params.require(:buddie).permit(:name,:age,:hobby,:hobby_description,:countryname,:neighborhood,:town,:photo,:level,:gender)

    end

  end


# .where("age = ? AND town LIKE ?","#{params[:age]}","%#{params[:town]}%").

app/views/buddies/index.html.erb
 <script
  src="https://code.jquery.com/jquery-3.2.1.min.js"
  integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
  crossorigin="anonymous"></script>
<div class="banner">


<!-- earch fields  -->

    <%= form_tag buddies_path,class: "search",method: :get do %>
  <div class="title country">country</div>
  <%= select_tag(:country, options_for_select(Countrie.all.pluck(:name) ,params[:country]))%>
  <div class="title town">city/town</div>
  <%= text_field_tag :town, params[:town] %>
  <div class="title town">hobby</div>
  <%= text_field_tag :hobby, params[:hobby] %>
  <div class="title within">distance(kilometers)</div>
  <%= select_tag(:distance, options_for_select([10,20,30,40,50,60,70,80],params[:distance]))%>
  <div class="title age">age</div>
  <%= select_tag(:age, options_for_select([['18-25'],['26-30'],['31-35'],['36-40'],['41-45'],['46-50'],['51-60'],['61-70'],['70+']] ,params[:age]))%>
  <div class="input">*gender</div>
  <%= select_tag(:gender, options_for_select([['male'],['female']] ,params[:gender]))%>
  <%= submit_tag "Search", name: nil%>
  <% end %>
    <%flag = 0%>
<div class="container">
  <div><%=link_to 'show all' ,buddies_path,class:"btn-success"%></div>
   <div class="row all_buddies">
  <%@buddies.each do |buddie|%>
  <div class="col-lg-2 col-md-6 col-6">

    <%=link_to show_other_buddie_buddy_path(buddie) do%>
           <%flag +=1%>
     <% if buddie.photo.blank? == false%>
        <div class="card" id="card<%=flag%>" name="<%=buddie.name%>"style="background:linear-gradient(rgba(0,0,0,.35), rgba(0,0,0,.35)),url(<%=cl_image_path "#{buddie.photo}"%>); border: solid white 1px;box-shadow: 5px 5px 5px;background-position: center;background-size: 100% 100%;">
          <%elsif buddie.gender == "male"%>
          <div class="card" id="card<%=flag%>" name="<%=buddie.name%>"style="background:linear-gradient(rgba(0,0,0,.35), rgba(0,0,0,.35)),url(http://winkeyecare.com/wp-content/uploads/2013/03/Empty-Profile-Picture-450x450.jpg); border: solid white 1px;box-shadow: 5px 5px 5px;background-position: center;background-size: 100% 100%;">
            <%else%>
               <div class="card" id="card<%=flag%>" name="<%=buddie.name%>"style="background:linear-gradient(rgba(0,0,0,.35), rgba(0,0,0,.35)),url(https://www.alitumbas.av.tr/uploads/empty-profile-picture-woman.jpg); border: solid white 1px;box-shadow: 5px 5px 5px;background-position: center;background-size: 100% 100%;">
              <%end%>
               <div id="name"><%=buddie.name%></div><div id="hobby"><%=buddie.hobby%></div><div id="gender"><%=buddie.gender%></div><div id="age"><%=buddie.age%></div><div id="level"><%=buddie.level%></div>


        </div>
      </div>
  <%end%>
<%end%>
      </div>
  </div>
</div>
 <div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @buddies %>
    </div>
    <%= will_paginate @buddies, :container => false %>
  </div>



  <%if flash[:success].blank? == false%>
        <div id="confirmation"><%=flash[:success]  %></div>
        <%end%>
 </div>
</div>
<style>
  .btn-success {padding:20px;width:100px;margin-top:3000px;border-radius:15px;background-color:#fbfafa;
}
  .search{position: absolute;top: 278px;left: 10px;}
  #confirmation{margin-top:10px;}
  .digg_pagination {
    position:absolute;
    top: 830px;
    left: 700px;
}

  p{position:absolute;top:100px;font-size:40px;}
  .container{position:absolute;top: 159px;left: 308px;}


  .banner

{
  margin-top:-17px;
  height:100vh;
  justify-content:center;
  color:white;
  background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://res.cloudinary.com/erezfriemagor/image/upload/v1555322198/basketball-court-black-and-white-casual-428318.jpg');
  background-position: center;
  background-size:100% 100%;

}
table{width:500px;margin-left:20px;position:absolute;top:200px;border-spacing:0 15px;border-collapse:separate; border: 3px solid white;font-size:23px;border-spacing: 1em .5em;}


.card {
  text-shadow: 0 1px 3px rgba(0,0,0,0.6);
  background-size: cover !important;
  background-position: center;
  color: white;
  position: relative;
  height:18vh;
  width:8vw;
  margin-top:144px;


}
.buddies
{
  position:absolute;
  top:100px;
}

 @media (max-width:767px){
  .card{width: 44vw;
    margin-left: -56px;}
  .container {top:505px;left: 49px;}
  .digg_pagination {position: absolute;top: 2182px;left: 74px;
}
.banner
{
  height:2400px;
}

}


@media only screen and (max-width: 1200px) and (min-width: 767px)  {
 .card{width:35vw;margin-left:-16px;height:230px;}
 .container{top:178px;}
}

</style>
<script>

   $( document ).ready(function() {


     $( ".card" ).hover(function() {
      var contentToRemove = document.querySelectorAll("p");
      $(contentToRemove).remove();
      let full_info = $(this).html();
      let temp_for_name = full_info.substr(31);
      let temp_for_hobby = full_info.substr(56);
      let just_name = temp_for_name.split('<')[0];
      let just_hobby = temp_for_hobby.split('<')[0];
 if (just_hobby.includes(">")) {

      just_hobby =  just_hobby.split('>')[1];

    }
      let temp_for_age = full_info.split('ge">')[1];
      let just_age = temp_for_age.split('<')[0];
      if (just_age.includes(">")){
      just_age = just_age.split('>')[1];
      }
      let p = document.createElement("p");
      let line_break = document.createElement("br");
      let line_break2= document.createElement("br");
      p.append("Name: ");
      p.append(just_name);
      p.append(line_break);
      p.append("Hobby: ")
      p.append(just_hobby);
      p.append(line_break2);
      p.append("Age:");
      p.append(just_age);
      $(".container").after(p);



});

    function makebannersmaller() {

      let  smallscreen = window.matchMedia("(max-width:700px)");
      let num = 0
      $( ".card" ).each(function() {
       num += 1;

      });

      if (smallscreen.matches) {
       if (num < 3){
          $(".banner").css("height","1000px");
          $(".digg_pagination").css("top","1000px");
          $(".container").css("top","500px");
       }
      else if (num < 7){
          $(".banner").css("height","1500px");
          $(".digg_pagination").css("top","1500px");
          $(".container").css("top","650px");
       }


      }

     }

    makebannersmaller();


   });

</script>




<!-- if (smallscreen.matches) {
        if (num < 7) {
          alert("good");
          $(.banner).css("height","800px");
        }

      } -->

app/views/buddies/new.html.erb
<div class="banner">
  <p id="flash">
  <%if flash[:faill].blank? == false%>
  <%=flash[:faill]%><br>
  <%end%>
  <%if flash[:name].blank? == false%>
  <%=flash[:name]%><br>
  <%end%>
  <%if flash[:hobby].blank? == false%>
  <%=flash[:hobby]%><br>
  <%end%>
  <%if flash[:town].blank? == false%>
  <%=flash[:town]%><br>
  <%end%>
   <%if flash[:town].blank? == false%>
  <%=flash[:town]%>
  <%end%>
</p>

  <div class="create_profile">
   <%= simple_form_for Buddie.new do |f| %>
   <div class="input">name</div>
   <%= f.input :name,label: false,maxlength: 15%>
   <div class="input">*age</div>
   <%= f.select :age, [['18-25'],['26-30'],['31-35'],['36-40'],['41-45'],['46-50'],['51-60'],['61-70'],['70+']]%>
   <div class="input">*gender</div>
   <%= f.select :gender, [['male'],['female']]%>
   <div class="input">*what is your hobby</div>
   <%= f.input :hobby,label: false,maxlength: 20%>
   <div class="input">tell us about your hobby</div>
   <%= f.text_area :hobby_description,label: false,size: "40x5",maxlength: 200 %>
   <div class="input" >*country</div>
   <%= f.collection_select(:countryname, Countrie.all, :name, :name,maxlength: 40) %>
   <div class="input">*city/town</div>
   <%= f.input :town,:label => false ,maxlength: 30%>
   <div class="input">neighborhood</div>
   <%= f.input :neighborhood,:label => false,maxlength: 30%>
   <div class="input">*your level</div>
    <%= f.select :level, [['begginer'],['intemidiate'],['professional'],["not sure/haven't played for a while" ]]%>
   <div class="input photo">upload a photo</div>
   <%= f.input :photo,:label => false %>
   <%= f.input :photo_cache, as: :hidden %>
   <div><%= f.button :submit,'submit', class: "btn-success training_btn"%><% end %>

   </div>


 </div>

<style>
@media (max-width:767px){
 .input
 {
  width:190px;
 }
 #buddie_hobby_description{width:319px;}
 #buddie_photo{width:100px;}
 #buddie_name{width:319px;}
 #buddie_hobby{width:319px;}
 #buddie_town{width:319px;}
 #buddie_neighborhood{width:319px;}
 .training_btn{margin-bottom:-50px;}
 #flash{margin-left:50px;width:192px;}


}
#flash{color:red;}
  .banner
{
  margin-top:-17px;
  height:100vh;
  justify-content:center;
  color:white;
  background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/342361/pexels-photo-342361.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');

}

.create_profile

 {
    width:15vw;
   color:black;
   margin-left:10px;

 }

 .input
 {
 font-size: 2.3vh;
 font-weight: lighter;
 color: white;
 font-style: bold;
 height: 2vh;
 margin-bottom: 1.7vh;
 }
 #buddie_age
 {
  width:120px;
 }



</style>

app/views/buddies/show.html.erb
<div class="banner">
  <%if @buddie[0][:photo] != nil%>
   <div class="photo" style="background-image:linear-gradient(rgba(0,0,0,.35),
  rgba(0,0,0,.35)),url(<%=cl_image_path "#{@buddie[0].photo}"%>);">
   </div>
   <%elsif @buddie[0].gender == "male" %>
   <div class="photo" style="background-image:linear-gradient(rgba(0,0,0,.35),
  rgba(0,0,0,.35)),url(http://winkeyecare.com/wp-content/uploads/2013/03/Empty-Profile-Picture-450x450.jpg);">
   </div>
   <%else%>
   <div class="photo" style="background-image:linear-gradient(rgba(0,0,0,.35),
  rgba(0,0,0,.35)),url(https://www.alitumbas.av.tr/uploads/empty-profile-picture-woman.jpg);">
   </div>
  <%end%>
  <div id="heading_box">
    <table>
    <tr><th></th><th></th></tr>
   <tr><td><h2 class="info">Name:</h2></td><td><div class="attribute"><%=@buddie[0].name%></div></td></tr>
    <tr><td><h2 class="info">Age:</h2></td><td><div class="attribute"><%=@buddie[0].age%></div></td></tr>
    <tr><td><h2 class="info">Hobby:</h2></td><td><div class="attribute"><%=@buddie[0].hobby%></div></td></tr>
    <tr><td><h2 class="info">location:</h2></td><td><div class="attribute"><%=@buddie[0].address%></div></td></tr>
    </table>
  </div>
   <p id="hobby_description"><%=@buddie[0].hobby_description%></p>

      <% if user_signed_in?%>
          <% if (current_user.has_profile == true)%>

          <%if @buddie[0].user_id != current_user.id%>
             <%= link_to "send a message", new_buddy_message_path(@buddie[0]), class: "btn btn-primary"%>
             <%else%>
              <%= link_to "my messages", buddy_messages_path(@buddie[0]), class: "btn btn-primary"%>
            <%end%>

          <%end%>
        <%end%>

  </div>



<style>
  .btn-primary{margin-left:15px;}
  table{margin-left:30px;}
  .attribute{font-size:20px;padding-left:10px;}
  #hobby_description{width:1200px;margin-left:20px;margin-top:50px;font-size:20px;}
  .info{font-weight:bold;padding-left:20px;}
 #heading_box{width:auto;margin-left:30px;border:solid;margin-top:87px;max-width: 300px;}
 .line{padding-left:20px;}
 .banner
{
  position:absolute;
  width:100vw;
  height:100vh;
  justify-content:center;
  color:white;
  background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/1389098/pexels-photo-1389098.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
  margin-top:-7px;

}
.photo
{
  width:230px;
  height:200px;
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
  position:absolute;
  top:50px;
  right:100px;

}
@media (max-width:767px){
#heading_box{margin-top:18px;margin-left:13px;}
#hobby_description{margin-top:200px; width:280px;}
.photo{top:192px;right:50px;}
}

</style>





1

app/views/buddies/show_other_buddie.html.erb
<div class="banner">
  <%if @buddie[:photo] != nil%>
   <div class="photo" style="background-image:linear-gradient(rgba(0,0,0,.35),
  rgba(0,0,0,.35)),url(<%=cl_image_path "#{@buddie.photo}"%>);">
   </div>
   <%elsif @buddie.gender == "male" %>
   <div class="photo" style="background-image:linear-gradient(rgba(0,0,0,.35),
  rgba(0,0,0,.35)),url(http://winkeyecare.com/wp-content/uploads/2013/03/Empty-Profile-Picture-450x450.jpg);">
   </div>
   <%else%>
   <div class="photo" style="background-image:linear-gradient(rgba(0,0,0,.35),
  rgba(0,0,0,.35)),url(https://www.alitumbas.av.tr/uploads/empty-profile-picture-woman.jpg);">
   </div>
  <%end%>
  <div id="heading_box">
    <table>
    <tr><th></th><th></th></tr>
   <tr><td><h2 class="info">Name:</h2></td><td><div class="attribute"><%=@buddie.name%></div></td></tr>
    <tr><td><h2 class="info">Age:</h2></td><td><div class="attribute"><%=@buddie.age%></div></td></tr>
    <tr><td><h2 class="info">Hobby:</h2></td><td><div class="attribute"><%=@buddie.hobby%></div></td></tr>
    <tr><td><h2 class="info">location:</h2></td><td><div class="attribute"><%=@buddie.address%></div></td></tr>
    </table>
  </div>
   <p id="hobby_description"><%=@buddie.hobby_description%></p>

      <% if user_signed_in?%>
          <% if (current_user.has_profile == true)%>

          <%if @buddie.user_id != current_user.id%>
             <%= link_to "send a message", new_buddy_message_path(@buddie), class: "btn btn-primary"%>
             <%else%>
              <%= link_to "my messages", buddy_messages_path(@buddie), class: "btn btn-primary"%>
            <%end%>

          <%end%>
        <%end%>
  </div>



<style>
  .btn-primary{margin-left:15px;}
  table{margin-left:30px;}
  .attribute{font-size:20px;padding-left:10px;}
  #hobby_description{width:1200px;margin-left:20px;margin-top:50px;font-size:20px;}
  .info{font-weight:bold;padding-left:20px;}
 #heading_box{width:auto;margin-left:30px;border:solid;margin-top:87px;max-width: 454px;}
 .line{padding-left:20px;}
 .banner
{
  position:absolute;
  width:100vw;
  height:100vh;
  justify-content:center;
  color:white;
  background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://images.pexels.com/photos/1389098/pexels-photo-1389098.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940');
  margin-top:-7px;

}
.photo
{
  width:230px;
  height:200px;
  background-size: cover;
  background-repeat: no-repeat;
  background-position: center;
  position:absolute;
  top:50px;
  right:100px;

}
@media (max-width:767px){
#heading_box{margin-top:18px;margin-left:13px;}
#hobby_description{margin-top:200px; width:280px;}
.photo{top:192px;right:50px;}
}

</style>





1